Classes de Tripulação, Avião, Recursos, Pista, Escala de voo
pedro-psb/sistema-aeroporto pull request #3
Opened 2024-06-09 22:36 UTC by Glaucus-M-Alm

- Implementação de novas classes
- adição das novas classes no include.hpp
- adição de métodos construtores vazios nas classes anteriores

2024-06-09 23:17 UTC, pedro-psb requested changes
Acho que vale a pena modificar as partes que comentei para usar vetores e ponteiros.
No mais parece ok.

2024-06-09 23:17 UTC, pedro-psb commented on src/FlightSchedule.hpp
FlightSchedule é tipo EscalaDeVoo, certo?
Acho que deve ser um vetor de ponteiro para voos:
```cpp
#include <vector>
using std::vector

class FlightSchedule{
    private:
        vector<Flight*> flights;
        // o numero de voos é o tamanho do vetor
    public:
        FlightSchedule();
        vector<Flight*> getFlights();
        void setFlights(vector<Flight*> flights);
};
```

2024-06-09 23:17 UTC, pedro-psb commented on src/BoardingCrew.hpp
> +        Steward* Stewards;
Acho que devemos trabalhar com ponteiros, porque esse objects nao sao especificos do escopo de `BoardingCrew` (eles podem ser usados em outros lugares)

```cpp
Pilot *Pilot
Pilot *Copilot
vector<Steward*> // vetor de aeoromoças
```

2024-06-09 23:17 UTC, pedro-psb commented on src/BoardingCrew.hpp
> +        Steward* Stewards;
Aí tb não precisaria desses `numStewards`, porque é o tamanho do `vector`.

2024-06-09 23:17 UTC, pedro-psb commented on src/BoardingCrew.hpp
> +        Steward* Stewards;
Alguns exemplos do professor usando ponteiros em situações semelhantes:

https://github.com/rocarvalhoufmg/pds/blob/23de9377fb824d919efdd4dfa1fc360917b50a3f/exercicios/simulador/core-simulador-hpp/Personagem.hpp#L17-L19

https://github.com/rocarvalhoufmg/pds/blob/23de9377fb824d919efdd4dfa1fc360917b50a3f/exercicios/simulador/core-simulador-hpp/Simulador.hpp#L13-L15

2024-06-09 23:52 UTC, pedro-psb approved these changes

2024-06-09 23:55 UTC, pedro-psb commented
Aprovei pra agilizar o processo, podemos melhorar essas coisas em outra iteração.
Mas se puder/quiser mexer nesse PR antes da Amanda revisar fique a vontade.

2024-06-10 12:36 UTC, Fiaux12 commented on src/BoardingCrew.hpp
> +        Steward* Stewards;
Concordo com o @pedro-psb, e melhor trabalhar com ponteiros. Se precisar de exemplos, eu fiz isso na classe Flight.

2024-06-10 12:39 UTC, Fiaux12 commented on src/Pilot.hpp
Não sei se é uma boa ideia criar construtores vazios para a maioria das classes. Não faz sentido criar um piloto sem nome e licença por exemplo. Acho que depois a gente deveria remover esses construtores vazios.

2024-06-10 12:42 UTC, Fiaux12 approved these changes
Precisamos de algumas mudanças, mas elas podem ser feitas depois para agilizar o trabalho.
Aprovado  ✔️

2024-06-10 12:43 UTC, merged